pg_custom_queries:
  - metric_name: pg_database_size_bytes
    query: "SELECT datname, pg_database_size(datname) as size_bytes FROM pg_database"
    metrics:
      - datname:
          usage: "LABEL"
          description: "Name of the database"
      - size_bytes:
          usage: "GAUGE"
          description: "Size of the database in bytes" 