version: 2.1

# (Facultatif) On peut retirer la section "orbs" si on n'utilise pas
# de "node: circleci/node@..." plus loin.
# orbs:
#   node: circleci/node@5

jobs:
  build-node:
    docker:
      - image: cimg/node:16.20
    working_directory: ~/project/apps/frontend
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Install pnpm
          command: |
            corepack enable
            corepack prepare pnpm@latest --activate

      - run:
          name: Install dependencies
          command: |
            pnpm install

      - run:
          name: Build
          command: |
            pnpm run build

      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts

      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true

      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  test:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/project/apps/backend
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}

      - run:
          name: Download Go modules
          command: go mod download

      - run:
          name: Run tests
          command: |
            go test -v ./test/...

      - store_test_results:
          path: junit.xml

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod

  build-go-executables:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/project/apps/backend
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}

      - run:
          name: Download Go modules
          command: go mod download

      - run:
          name: Create artifacts dir
          command: mkdir -p ~/artifacts

      - run:
          name: Build executables
          command: |
            go build -o ~/artifacts/my-api main.go

      - store_artifacts:
          path: ~/artifacts
          destination: executables

workflows:
  build-and-test:
    jobs:
      - test
      - build-node:
          requires:
            - test
      - build-go-executables:
          requires:
            - test
