apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: prod
  source:
    repoURL: "https://github.com/clementpnn/devops-project"
    targetRevision: main
    path: "k8s/"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
