name: CD Backend - Deploy to GCP Artifact Registry & Cloud Run

on:
  push:
    tags:
      - "v*.*.*"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION_DEV: europe-west3
  GCP_REGION_PROD: europe-west9
  SERVICE_NAME: devopv-backend
  REPO_NAME: devopv-artifact-repo
  DOCKERFILE_PATH: ./apps/backend/Dockerfile

jobs:
  build-and-push:
    name: Build & Push Docker Image to Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG=$TAG_NAME" >> $GITHUB_ENV
          if [[ "$TAG_NAME" == *"-dev" ]]; then
            echo "DEPLOY_REGION=${{ env.GCP_REGION_DEV }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_REGION=${{ env.GCP_REGION_PROD }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image from backend
        run: |
          docker build -t ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG }} -f ${{ env.DOCKERFILE_PATH }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG }}

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG }} \
            --region ${{ env.DEPLOY_REGION }} \
            --platform managed \
            --allow-unauthenticated
