name: CD FRONTEND

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Deployment Target
        id: target
        run: |
          TAG_NAME="${{ github.ref_name }}"
          echo "TAG_NAME=${TAG_NAME}"
          if [[ "$TAG_NAME" == *"-dev" ]]; then
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
            echo "SSH_HOST=${{ secrets.SSH_HOST_DE }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
            echo "SSH_HOST=${{ secrets.SSH_HOST_FR }}" >> $GITHUB_ENV
          fi

      - name: Prepare metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./apps/frontend/Dockerfile
          build-args: |
            APP_RELEASE=${{ github.sha }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy a new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            sudo docker compose pull frontend
            sudo docker compose up -d frontend
