name: CI BACKEND

on:
  push:
    paths:
      - "apps/backend/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/backend

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.*"

      - name: Run tests
        run: go test -v ./test/...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        shell: bash
        working-directory: apps/backend

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.*"

      - name: Build
        run: CGO_ENABLED=0 go build -a --trimpath --installsuffix cgo --ldflags="-s" -o main ./main.go
