name: CI Web

on:
  push:
    paths:
      - "apps/frontend/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm@9.4.0

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        shell: bash
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript
        run: pnpm type

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: typescript
    defaults:
      run:
        shell: bash
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: typescript
    defaults:
      run:
        shell: bash
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
